#!/bin/bash
  
# Programs
PYTHON="python3"    # Python version installed (3 or above)
MPI="mpirun"        # MPI
LAMMPS="lmp_mpi"    # LAMMPS program
THREADS=4           # The number of threads

# Files
SCRIPTS_DIR="../scripts/"                 # The directory for scripts
SAVE="../data/"                           # Directory to save data
IN_NAME="vp_steps.in"                     # The template name of the input file
TEMPLATE="../file_templates/${IN_NAME}"   # The run input file template

# Simulation variables
SET='../runs/nvt_Al236-Sm20/'                           # The name for the set of runs
RUNS=100                                                # The number of runs
POTENTIAL="../potentials/AlSm.eam.lammps.fs"            # The potential file
STYLE="eam/fs"                                          # LAMMPS potential style
INIT="../initial_trajectories/236-20.lammpstrj"         # The starting trajectory
ELEMENTS="Al Sm"                                        # Ordered elements in INIT
TIMESTEP=0.001                                          # The timestep
DUMP=100                                                # The data dump rate
HOLDTYPE="nvt"                                          # The type of holds (npt or nvt)

# NVT cube volumes per hold (none if npt)
VOLS="[5215.2464828303855, 4949.398984455958, 4778.643694530444]"

# Analysis variables
SIGMA=2

# The list of (hold, run steps) to simulate
HOLDS="[(1300, 15000), (800, 15000), (300, 15000)]"

# Generate nvt runs
${PYTHON} ${SCRIPTS_DIR}vp_run_creator.py\
	"${SET}"\
        "${RUNS}"\
        "${TEMPLATE}"\
        "${ELEMENTS}"\
        "${INIT}"\
        "${POTENTIAL}"\
        "${STYLE}"\
        "${TIMESTEP}"\
        "${DUMP}"\
        "${HOLDTYPE}"\
        "${VOLS}"\
        "${HOLDS}"\

# Run all created jobs
${PYTHON} ${SCRIPTS_DIR}run_lammps.py\
        "${SET}"\
        "${MPI} -n ${THREADS} ${LAMMPS}"\
        "${IN_NAME}"\

${PYTHON} ${SCRIPTS_DIR}thermo_plotter.py\
	"${SET}"\
	"${IN_NAME}"\
	"${SIGMA}"\
	"False"\
