#!/bin/bash

# Programs
PYTHON="python3"              # Python version installed (3 or above)

# Files
SCRIPTS_DIR="../scripts/"     # The directory for scripts
DATA="../data/"               # Directory were data is stored
SAVE="../data/"  # Directory to save fraction data

# Analysis variables
EDGES="5"                     # The Voronoi polyhedra edge index
FACES="10"                     # The Voronoi polyhedra minimum number of faces
THRESHOLD="0.0"               # The minimum edge length for a Voronoi polyhedra
EXT="_fractions_better.txt"   # Save extension

# The name of files containing trajectories
declare -a arr=("XDATCAR.300" "XDATCAR.800" "XDATCAR.1300")

# Calculate Vornoi polyhedra fractions
for i in "${arr[@]}"
do
	${PYTHON} ${SCRIPTS_DIR}vp_individual.py "-n${i}" "-d${DATA}" "-e${EDGES}" "-f${FACES}"	"-t${THRESHOLD}" "-s${SAVE}${i}${EXT}"
done
