#!/bin/bash

# Programs
PYTHON="python3"              # Python version installed (3 or above)

# Files
SCRIPTS_DIR="../scripts/"              # The directory for scripts
SAVE="../data/"                        # Directory to save data
TEMPLATE="../file_templates/steps.in"  # The run input file template

# Simulation variables
RUNS=50                                                 # The number of runs to generate
POTENTIAL="../potentials/AlSm.eam.lammps.fs"            # The potential file
STYLE="eam/fs"                                          # LAMMPS potential style
INIT="../initial_trajectories/Al-Sm_initial.lammpstrj"  # The starting trajectory
ELEMENTS="Al Sm"                                        # Ordered elements in INIT
TIMESTEP=0.001                                          # The timestep
DUMP=100                                                # The data dump rate
HOLDTYPE="npt"                                          # The type of holds (npt or nvt)
VOLS="none"                                             # NVT cube length per hold (none if npt)

# The (hold, run steps) to simulate
HOLDS="(1300, 15000) (800, 1500) (300, 1500)"


# Generate npt runs
${PYTHON} ${SCRIPTS_DIR}run-creator.py\
	${RUNS}\
        ${TEMPLATE}\
	${ELEMENTS}\
	${INIT}\
        ${POTENTIAL}\
	${STYLE}\
	${TIMESTEP}\
	${DUMP}\
	${HOLDTYPE}\
	${VOLS}\
	${HOLDS}\
