#!/bin/bash

# Generate runs

../relaxation_steps/run-creator.py\
	50\
        "../relaxation_steps/templates_lammps/steps.in"\
	"Al Sm"\
	"../../initial_trajectories/Al-Sm_initial.lammpstrj"\
        "../../relaxation_steps/potentials/AlSm.eam.lammps.fs"\
	"eam/fs"\
	0.001\
	100\
	"npt"\
	"none"\
	"(1300, 15000)"\

../relaxation_steps/execute-runs.py
